from typing import TypedDict, Dict, Any, Optional

# This is the state from your current branch (interactive-cli)
class SolverState(TypedDict):
    """
    Represents the state of the auto-solver agent.
    """
    # --- Inputs for the validation ---
    problem_statement: str
    num_test_generations: int
    max_iterations: int
    run_id: str
    bruteforce_time_limit: float  # Time limit in seconds for each bruteforce run

    # --- Code generated by initial nodes ---
    bruteforce_code: Optional[str]
    test_generator_code: Optional[str]
    solution_code: Optional[str]

    # --- State for the refinement loop ---
    test_cases_dir_path: Optional[str]
    test_results: Optional[Dict[str, Any]]
    iteration_count: int

    # --- Final output ---
    final_verdict: str

# This is the state from the incoming branch
class ValidationState(TypedDict):
    """
    Represents the state for validating a C++ solution.
    This is the central data structure for the validator graph.
    """
    # --- Inputs for the validation ---
    problem_statement: str
    solution_code: str          # The C++ code for the user's solution
    test_generator_code: str    # The C++ code for testcaseGenerator.cpp
    bruteforce_solution_code: str # The C++ code for the correct/bruteforce solution

    # --- Fields populated by the graph ---
    test_results: Optional[Dict[str, Any]]
    critique: Optional[str]
    verdict: Optional[str]

# You can add other state TypedDicts here in the future